#############################################################################
# Makefile for building: mathmod.app/Contents/MacOS/mathmod
# Generated by qmake (3.1) (Qt 5.15.15)
# Project:  mathmod.pro
# Template: app
# Command: /usr/local/Qt-5.15.15/bin/qmake -o mathmod.xcodeproj/project.pbxproj mathmod.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /usr/local/Qt-5.15.15/bin/qmake
mathmod.xcodeproj/project.pbxproj: mathmod.pro /usr/local/Qt-5.15.15/mkspecs/macx-clang/qmake.conf /usr/local/Qt-5.15.15/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.15.15/mkspecs/qdevice.pri \
		/usr/local/Qt-5.15.15/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.15.15/mkspecs/common/unix.conf \
		/usr/local/Qt-5.15.15/mkspecs/common/mac.conf \
		/usr/local/Qt-5.15.15/mkspecs/common/macx.conf \
		/usr/local/Qt-5.15.15/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.15.15/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.15.15/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Qt-5.15.15/mkspecs/common/clang.conf \
		/usr/local/Qt-5.15.15/mkspecs/common/clang-mac.conf \
		/usr/local/Qt-5.15.15/mkspecs/qconfig.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_ext_freetype.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_ext_libjpeg.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_ext_libpng.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.15.15/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.15.15/mkspecs/macx-clang/qmake.conf \
		/usr/local/Qt-5.15.15/mkspecs/macx-xcode/qmake.conf \
		/usr/local/Qt-5.15.15/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt-5.15.15/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/toolchain.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/mac/toolchain.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/mac/mac.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/qt.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/resources_functions.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/resources.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/moc.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/uic.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/qmake_use.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/file_copies.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/mac/rez.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.15.15/mkspecs/features/lex.prf \
		mathmod.pro \
		myressources.qrc \
		/usr/local/Qt-5.15.15/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		/usr/local/Qt-5.15.15/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/Qt-5.15.15/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Qt-5.15.15/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o mathmod.xcodeproj/project.pbxproj mathmod.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/usr/local/Qt-5.15.15/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.15.15/mkspecs/qdevice.pri:
/usr/local/Qt-5.15.15/mkspecs/features/device_config.prf:
/usr/local/Qt-5.15.15/mkspecs/common/unix.conf:
/usr/local/Qt-5.15.15/mkspecs/common/mac.conf:
/usr/local/Qt-5.15.15/mkspecs/common/macx.conf:
/usr/local/Qt-5.15.15/mkspecs/common/sanitize.conf:
/usr/local/Qt-5.15.15/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.15.15/mkspecs/common/gcc-base-mac.conf:
/usr/local/Qt-5.15.15/mkspecs/common/clang.conf:
/usr/local/Qt-5.15.15/mkspecs/common/clang-mac.conf:
/usr/local/Qt-5.15.15/mkspecs/qconfig.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_ext_freetype.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_ext_libjpeg.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_ext_libpng.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.15.15/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.15.15/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.15.15/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.15.15/mkspecs/macx-clang/qmake.conf:
/usr/local/Qt-5.15.15/mkspecs/macx-xcode/qmake.conf:
/usr/local/Qt-5.15.15/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Qt-5.15.15/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.15.15/mkspecs/features/mac/sdk.prf:
/usr/local/Qt-5.15.15/mkspecs/features/toolchain.prf:
/usr/local/Qt-5.15.15/mkspecs/features/mac/toolchain.prf:
/usr/local/Qt-5.15.15/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.15.15/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt-5.15.15/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.15.15/mkspecs/features/default_post.prf:
/usr/local/Qt-5.15.15/mkspecs/features/mac/default_post.prf:
/usr/local/Qt-5.15.15/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt-5.15.15/mkspecs/features/mac/mac.prf:
/usr/local/Qt-5.15.15/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.15.15/mkspecs/features/qt.prf:
/usr/local/Qt-5.15.15/mkspecs/features/resources_functions.prf:
/usr/local/Qt-5.15.15/mkspecs/features/resources.prf:
/usr/local/Qt-5.15.15/mkspecs/features/moc.prf:
/usr/local/Qt-5.15.15/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.15.15/mkspecs/features/uic.prf:
/usr/local/Qt-5.15.15/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.15.15/mkspecs/features/qmake_use.prf:
/usr/local/Qt-5.15.15/mkspecs/features/file_copies.prf:
/usr/local/Qt-5.15.15/mkspecs/features/mac/rez.prf:
/usr/local/Qt-5.15.15/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Qt-5.15.15/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.15.15/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.15.15/mkspecs/features/yacc.prf:
/usr/local/Qt-5.15.15/mkspecs/features/lex.prf:
mathmod.pro:
myressources.qrc:
/usr/local/Qt-5.15.15/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
/usr/local/Qt-5.15.15/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/Qt-5.15.15/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Qt-5.15.15/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o mathmod.xcodeproj/project.pbxproj mathmod.pro -spec macx-xcode

qmake_all: FORCE

